[app]
version = 1 # 0=debug 1=release
cacheDir = "./cache/"

[httpServer]
addr = ":8888"

[log]
dir = "./log/"

[db]
# 玩家、公告、反馈 的db地址
dsn = "devel:i18n@tcp(127.0.0.1:3306)/plan_activity?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
active = 200
idle = 10
idleTimeout = 345600
debug = true

[redis]
# 发布消息 的redis地址
addr = "127.0.0.1:6379"
password = "i18n!@#"
db = 0
