// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameActivityUser = "activity_user"

// ActivityUser mapped from table <activity_user>
type ActivityUser struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:活动报名id" json:"id"`                    // 活动报名id
	ActivityID int32     `gorm:"column:activity_id;not null;comment:活动id" json:"activity_id"`                         // 活动id
	UserID     int32     `gorm:"column:user_id;not null;comment:报名用户id" json:"user_id"`                               // 报名用户id
	Alias_     string    `gorm:"column:alias;comment:报名昵称" json:"alias"`                                              // 报名昵称
	IsFriend   int32     `gorm:"column:is_friend;not null;default:1;comment:是否朋友" json:"is_friend"`                   // 是否朋友
	CreateAt   time.Time `gorm:"column:create_at;not null;default:current_timestamp();comment:创建时间" json:"create_at"` // 创建时间
	UpdateAt   time.Time `gorm:"column:update_at;not null;default:current_timestamp();comment:修改时间" json:"update_at"` // 修改时间
	DeleteAt   time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                                      // 删除时间
}

// TableName ActivityUser's table name
func (*ActivityUser) TableName() string {
	return TableNameActivityUser
}
