// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGroupMember = "group_member"

// GroupMember mapped from table <group_member>
type GroupMember struct {
	ID       int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                    // 成员id
	GroupID  int32     `gorm:"column:group_id;not null" json:"group_id"`                             // 群组id
	UserID   int32     `gorm:"column:user_id;not null" json:"user_id"`                               // 用户id
	Scores   int32     `gorm:"column:scores;not null" json:"scores"`                                 // 积分
	Position int32     `gorm:"column:position;not null;default:1" json:"position"`                   // 群组职位
	Alias_   string    `gorm:"column:alias;not null" json:"alias"`                                   // 群组中别名
	Avator   string    `gorm:"column:avator" json:"avator"`                                          // 头像
	EnterAt  time.Time `gorm:"column:enter_at" json:"enter_at"`                                      // 进入群组时间
	CreateAt time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"` // 创建时间
	UpdateAt time.Time `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP" json:"update_at"` // 更新时间
	DeleteAt time.Time `gorm:"column:delete_at" json:"delete_at"`                                    // 删除时间
}

// TableName GroupMember's table name
func (*GroupMember) TableName() string {
	return TableNameGroupMember
}
