// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGroup = "group"

// Group mapped from table <group>
type Group struct {
	ID       int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                    // 群组ID
	Scores   int32     `gorm:"column:scores;not null" json:"scores"`                                 // 积分
	Level    int32     `gorm:"column:level;not null;default:1" json:"level"`                         // 群组等级
	Name     string    `gorm:"column:name;not null" json:"name"`                                     // 群组名称
	Logo     string    `gorm:"column:logo" json:"logo"`                                              // 群组LOGO
	Notice   string    `gorm:"column:notice" json:"notice"`                                          // 群组公告
	Addr     string    `gorm:"column:addr" json:"addr"`                                              // 群组总部地址
	CreateAt time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"` // 创建时间
	UpdateAt time.Time `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP" json:"update_at"` // 更新时间
	DeleteAt time.Time `gorm:"column:delete_at" json:"delete_at"`                                    // 删除时间
}

// TableName Group's table name
func (*Group) TableName() string {
	return TableNameGroup
}
