// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:用户ID" json:"id"`                      // 用户ID
	Username  string    `gorm:"column:username;not null;comment:用户名" json:"username"`                                // 用户名
	Password  string    `gorm:"column:password;not null;default:123456;comment:密码" json:"password"`                  // 密码
	Scores    int32     `gorm:"column:scores;not null;comment:积分" json:"scores"`                                     // 积分
	Token     string    `gorm:"column:token;not null;comment:token" json:"token"`                                    // token
	WxToken   string    `gorm:"column:wx_token;not null;comment:微信session_key" json:"wx_token"`                      // 微信session_key
	WxNick    string    `gorm:"column:wx_nick;not null;comment:微信昵称" json:"wx_nick"`                                 // 微信昵称
	Nick      string    `gorm:"column:nick;not null;comment:昵称" json:"nick"`                                         // 昵称
	Avatar    string    `gorm:"column:avatar;comment:头像" json:"avatar"`                                              // 头像
	Gender    int32     `gorm:"column:gender;not null;default:1;comment:性别:1男,2女" json:"gender"`                     // 性别:1男,2女
	Phone     string    `gorm:"column:phone;comment:手机号码" json:"phone"`                                              // 手机号码
	Email     string    `gorm:"column:email;comment:邮箱" json:"email"`                                                // 邮箱
	Addr      string    `gorm:"column:addr;comment:住址" json:"addr"`                                                  // 住址
	IP        string    `gorm:"column:ip;default:0;comment:ip地址" json:"ip"`                                          // ip地址
	LoginAt   time.Time `gorm:"column:login_at;comment:登录时间" json:"login_at"`                                        // 登录时间
	OfflineAt time.Time `gorm:"column:offline_at;comment:离开时间" json:"offline_at"`                                    // 离开时间
	CreateAt  time.Time `gorm:"column:create_at;not null;default:current_timestamp();comment:创建时间" json:"create_at"` // 创建时间
	UpdateAt  time.Time `gorm:"column:update_at;not null;default:current_timestamp();comment:更新时间" json:"update_at"` // 更新时间
	DeleteAt  time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                                      // 删除时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
