// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                    // 用户ID
	Username  string    `gorm:"column:username;not null" json:"username"`                             // 用户名
	Password  string    `gorm:"column:password;not null;default:123456" json:"password"`              // 密码
	Scores    int32     `gorm:"column:scores;not null" json:"scores"`                                 // 积分
	Token     string    `gorm:"column:token;not null" json:"token"`                                   // token
	WxToken   string    `gorm:"column:wx_token;not null" json:"wx_token"`                             // 微信session_key
	WxNick    string    `gorm:"column:wx_nick;not null" json:"wx_nick"`                               // 微信昵称
	Nick      string    `gorm:"column:nick;not null" json:"nick"`                                     // 昵称
	Sex       int32     `gorm:"column:sex;not null;default:1" json:"sex"`                             // 性别:1男,2女
	Phone     string    `gorm:"column:phone" json:"phone"`                                            // 手机号码
	Email     string    `gorm:"column:email" json:"email"`                                            // 邮箱
	IP        string    `gorm:"column:ip;default:0" json:"ip"`                                        // ip地址
	LoginAt   time.Time `gorm:"column:login_at" json:"login_at"`                                      // 登录时间
	OfflineAt time.Time `gorm:"column:offline_at" json:"offline_at"`                                  // 离开时间
	CreateAt  time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"` // 创建时间
	UpdateAt  time.Time `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP" json:"update_at"` // 更新时间
	DeleteAt  time.Time `gorm:"column:delete_at" json:"delete_at"`                                    // 删除时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
